# Proyecto de Limpieza de Datos con Python #
### Objetivo del Proyecto ###
En este proyecto, abordaremos la tarea fundamental de limpieza de datos utilizando Python, centrándonos en un conjunto de datos relacionado con Auditorias del Sistema de Gestión. Este conjunto de datos, obtenido de una empresa de manufactura, está vinculado a la fabricación de insumos para la industría minera.

### Pasos para la Limpieza de Datos
1. Identificación y Eliminación de Valores Atípicos o Faltantes:
    * Identificaremos y abordaremos cualquier valor atípico que pueda distorsionar la calidad de los datos.
    * Eliminaremos cualquier entrada que contenga valores faltantes, asegurando así la integridad de nuestros resultados.

2. Eliminación de Datos Duplicados:
    * Detectaremos y eliminaremos duplicados para garantizar la singularidad de los registros en nuestro conjunto de datos.
3. Conversión de Datos al Formato Adecuado:
    * Aseguraremos que todos los datos estén en el formato correcto para su posterior análisis.

4. Normalización de Datos:
    * Normalizaremos los datos para garantizar consistencia y facilitar comparaciones significativas.

5. Verificación de Consistencia de Datos:
    * Realizaremos controles de coherencia en los datos para identificar posibles discrepancias internas.

6. Verificación de Validez de Datos:
    * Verificaremos la validez de los datos, asegurándonos de que cumplan con las expectativas y criterios establecidos.

### Algoritmo de Limpieza de Datos con Python
1. Importar el conjunto de datos en Python.
2. Eliminar valores atípicos y faltantes.
3. Eliminar datos duplicados.
4. Convertir los datos al formato adecuado.
5. Normalizar los datos.
6. Verificar la consistencia y validez de los datos.
7. Exportar el conjunto de datos limpio a un nuevo archivo.

### Conjunto de Datos del Proyecto
Los datos crudos se encuentran en formato xlsx y se han obtenido de fuentes directa del cliente. Este archivo xlsx contiene información crucial, como la fecha de Inicio y Fin, estado de la auditoria, auditor, sector auditado, entre otros. La calidad de estos datos es esencial para un análisis preciso y significativo en el ámbito de las auditorias del sistema de gestión de la empresa.

In [1]:
# Cargar los datos
import pandas as pd
archivo_excel = r'C:\Users\HP\Desktop\IntiMetrix\Datos\Datos_AUD.xlsx'
df = pd.read_excel(archivo_excel)
df

,IdSolicitud,EstadoId,FechaCierre,FechaInicio,FechaFin,iYear,iMonth,iMonthT,iLocation,iNroCompleto,...,iNCAsocMenor,iNCAsociadas,iAMAsociadas,iACAsocCriticas,iACAsocMayor,iACAsocMenor,iACAsociadas,CerradoADestiempo,CerradoAtiempo,iLink
0,2706,6,2015-08-01,2015-08-01,2015-08-31,2015,8,08-Aug,APA,AUD-S000001,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
1,2707,6,2015-08-10,2015-08-10,2015-09-16,2015,8,08-Aug,APA,AUD-S000002,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2,2708,6,2015-08-01,2015-08-01,2015-08-31,2015,8,08-Aug,APA,AUD-S000003,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
3,2709,6,2015-08-01,2015-08-01,2015-08-31,2015,8,08-Aug,APA,AUD-S000004,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
4,2710,6,2015-08-01,2015-08-01,2015-08-31,2015,8,08-Aug,APA,AUD-S000005,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2583,42132,6,2023-09-04,2023-06-01,2023-06-30,2023,6,2023-06-06 00:00:00,APA,AUD-S002586,...,0,0,0,0,0,0,0,1,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2584,45584,2,2023-10-26,2023-10-01,2023-10-30,2023,10,2023-10-10 00:00:00,APA,AUD-S002587,...,0,0,1,0,0,0,1,0,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2585,45587,2,2023-10-26,2023-10-01,2023-10-01,2023,10,2023-10-10 00:00:00,APA,AUD-S002588,...,0,0,0,0,0,0,0,0,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2586,45589,2,2023-10-30,2023-12-01,2023-12-31,2023,12,12-Dec,APA,AUD-S002589,...,0,0,0,0,0,0,0,0,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2587,45593,2,2023-11-10,2023-12-01,2023-12-01,2023,12,12-Dec,APA,AUD-S002590,...,0,0,0,0,0,0,0,0,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...

In [2]:
# exploración de datos
df.head()

,IdSolicitud,EstadoId,FechaCierre,FechaInicio,FechaFin,iYear,iMonth,iMonthT,iLocation,iNroCompleto,...,iNCAsocMenor,iNCAsociadas,iAMAsociadas,iACAsocCriticas,iACAsocMayor,iACAsocMenor,iACAsociadas,CerradoADestiempo,CerradoAtiempo,iLink
0,2706,6,2015-08-01,2015-08-01,2015-08-31,2015,8,08-Aug,APA,AUD-S000001,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
1,2707,6,2015-08-10,2015-08-10,2015-09-16,2015,8,08-Aug,APA,AUD-S000002,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2,2708,6,2015-08-01,2015-08-01,2015-08-31,2015,8,08-Aug,APA,AUD-S000003,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
3,2709,6,2015-08-01,2015-08-01,2015-08-31,2015,8,08-Aug,APA,AUD-S000004,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...
4,2710,6,2015-08-01,2015-08-01,2015-08-31,2015,8,08-Aug,APA,AUD-S000005,...,0,0,0,0,0,0,0,0,1,https://apa-austinpowder.kahunasoft.com.ar/#/s...

In [3]:
df.tail()

,IdSolicitud,EstadoId,FechaCierre,FechaInicio,FechaFin,iYear,iMonth,iMonthT,iLocation,iNroCompleto,...,iNCAsocMenor,iNCAsociadas,iAMAsociadas,iACAsocCriticas,iACAsocMayor,iACAsocMenor,iACAsociadas,CerradoADestiempo,CerradoAtiempo,iLink
2583,42132,6,2023-09-04,2023-06-01,2023-06-30,2023,6,2023-06-06 00:00:00,APA,AUD-S002586,...,0,0,0,0,0,0,0,1,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2584,45584,2,2023-10-26,2023-10-01,2023-10-30,2023,10,2023-10-10 00:00:00,APA,AUD-S002587,...,0,0,1,0,0,0,1,0,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2585,45587,2,2023-10-26,2023-10-01,2023-10-01,2023,10,2023-10-10 00:00:00,APA,AUD-S002588,...,0,0,0,0,0,0,0,0,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2586,45589,2,2023-10-30,2023-12-01,2023-12-31,2023,12,12-Dec,APA,AUD-S002589,...,0,0,0,0,0,0,0,0,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...
2587,45593,2,2023-11-10,2023-12-01,2023-12-01,2023,12,12-Dec,APA,AUD-S002590,...,0,0,0,0,0,0,0,0,0,https://apa-austinpowder.kahunasoft.com.ar/#/s...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2588 entries, 0 to 2587
Data columns (total 41 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   IdSolicitud                 2588 non-null   int64
 1   EstadoId                    2588 non-null   int64
 2   FechaCierre                 2588 non-null   datetime64[ns]
 3   FechaInicio                 2588 non-null   datetime64[ns]
 4   FechaFin                    2588 non-null   datetime64[ns]
 5   iYear                       2588 non-null   int64
 6   iMonth                      2588 non-null   int64
 7   iMonthT                     2588 non-null   object
 8   iLocation                   2588 non-null   object
 9   iNroCompleto                2588 non-null   object
 10  DescripcionResumida         2588 non-null   object
 11  iAuditor                    2571 non-null   object
 12  iSubSite                    1072 non-null   object
 13  iSite                       1072 non-null   object
 14  iMasSite                    1051 non-null   object
 15  iShesElement                1074 non-null   object
 16  iStep                       2588 non-null   int64
 17  iPlanificadas               2588 non-null   int64
 18  iFuture                     2588 non-null   int64
 19  iCanceladas                 2588 non-null   int64
 20  iCerradas                   2588 non-null   int64
 21  iEnEjecucion                2588 non-null   int64
 22  iEjecConProcesosPendientes  2588 non-null   int64
 23  iPendientedeHacer           2588 non-null   int64
 24  iConProcesosPendientes      2588 non-null   int64
 25  iPlanificada                2588 non-null   int64
 26  iCerrada                    2588 non-null   int64
 27  iPendientedeCerrar          2588 non-null   int64
 28  iFueraFecha                 2588 non-null   int64
 29  iNCAsocCriticas             2588 non-null   int64
 30  iNCAsocMayor                2588 non-null   int64
 31  iNCAsocMenor                2588 non-null   int64
 32  iNCAsociadas                2588 non-null   int64
 33  iAMAsociadas                2588 non-null   int64
 34  iACAsocCriticas             2588 non-null   int64
 35  iACAsocMayor                2588 non-null   int64
 36  iACAsocMenor                2588 non-null   int64
 37  iACAsociadas                2588 non-null   int64
 38  CerradoADestiempo           2588 non-null   int64
 39  CerradoAtiempo              2588 non-null   int64
 40  iLink                       2588 non-null   object
dtypes: datetime64[ns](3), int64(28), object(10)
memory usage: 829.1+ KB

In [5]:
df.describe()

,IdSolicitud,EstadoId,FechaCierre,FechaInicio,FechaFin,iYear,iMonth,iStep,iPlanificadas,iFuture,...,iNCAsocMayor,iNCAsocMenor,iNCAsociadas,iAMAsociadas,iACAsocCriticas,iACAsocMayor,iACAsocMenor,iACAsociadas,CerradoADestiempo,CerradoAtiempo
count,2588.000000,2588.000000,2588,2588,2588,2588.000000,2588.000000,2588.000000,2588.0,2588.000000,...,2588.000000,2588.000000,2588.000000,2588.000000,2588.000000,2588.000000,2588.000000,2588.000000,2588.000000,2588.000000
mean,11188.136785,5.931994,2019-04-17 20:19:06.213292288,2019-03-20 14:21:53.137558016,2019-04-19 08:39:41.452859136,2018.700541,6.780139,5.931994,1.0,0.000773,...,0.010046,0.003478,0.016615,0.044049,0.003091,0.021252,0.012365,0.038640,0.227975,0.755023
min,2706.000000,2.000000,2015-08-01 00:00:00,2015-08-01 00:00:00,2015-08-15 00:00:00,2015.000000,1.000000,2.000000,1.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3380.750000,6.000000,2017-03-31 00:00:00,2017-03-31 00:00:00,2017-04-29 00:00:00,2017.000000,4.000000,6.000000,1.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,4068.500000,6.000000,2018-10-31 00:00:00,2018-10-16 00:00:00,2018-11-29 00:00:00,2018.000000,7.000000,6.000000,1.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,19507.250000,6.000000,2021-04-27 06:00:00,2021-04-01 00:00:00,2021-04-30 00:00:00,2021.000000,10.000000,6.000000,1.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,45593.000000,6.000000,2023-11-10 00:00:00,2023-12-01 00:00:00,2023-12-31 00:00:00,2023.000000,12.000000,6.000000,1.0,1.000000,...,3.000000,2.000000,5.000000,3.000000,1.000000,8.000000,10.000000,11.000000,1.000000,1.000000
std,12491.946663,0.517207,NaN,NaN,NaN,2.385606,3.332838,0.517207,0.0,0.027794,...,0.120780,0.076067,0.184734,0.257082,0.055523,0.237425,0.243671,0.414343,0.419608,0.430157

In [6]:
df.isnull()

,IdSolicitud,EstadoId,FechaCierre,FechaInicio,FechaFin,iYear,iMonth,iMonthT,iLocation,iNroCompleto,...,iNCAsocMenor,iNCAsociadas,iAMAsociadas,iACAsocCriticas,iACAsocMayor,iACAsocMenor,iACAsociadas,CerradoADestiempo,CerradoAtiempo,iLink
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2583,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2584,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2585,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2586,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2587,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### Limpieza de datos

In [7]:
# Eliminar las filas que tienen null en filas especificas
# Definir las columnas específicas para eliminar filas nulas
columnas_especificas = ['iSubSite', 'iSite']

# Eliminar filas nulas solo para las columnas especificadas
df = df.dropna(subset=columnas_especificas)

In [8]:
# Completamos filas que tengan null en base al valor de la siguiente fila

df = df.fillna(method='bfill')

C:\Users\HP\AppData\Local\Temp\ipykernel_8440\2864368825.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='bfill')

In [9]:
# Corrección de errores
# Definimos la lista de nombre de columnas fecha
columnas_fechas = ['FechaCierre','FechaInicio','FechaFin']

# Convertimos columnas fecha al formato dd/mm/yyyy

df[columnas_fechas] = df[columnas_fechas].apply(lambda x: x.dt.strftime('%d/%m/%Y'))

In [10]:
#Eliminar columnas que no se necesiten
#Definir las columnas que se van a eliminar
Columnas_a_eliminar = ['iYear','iMonth','iMonthT','iLocation','iLink','DescripcionResumida','iStep']

#Eliminar las columnas especificadas
df = df.drop(Columnas_a_eliminar, axis=1)

In [11]:
# Condicionalmente reemplazar los valores en 'iSite' cuando 'iSite' es 'PADRE-SECTORAUDITAR'
df.loc[df['iSite'] == 'PADRE-SECTORAUDITAR', 'iSite'] = df['iSubSite']

In [12]:
# Aplicar la división en cada columna
columnas_a_procesar = ['iSubSite', 'iSite', 'iMasSite']

df[columnas_a_procesar] = df[columnas_a_procesar].applymap(lambda x: str(x).split('-', 1)[-1]).applymap(lambda x: x.strip())

C:\Users\HP\AppData\Local\Temp\ipykernel_8440\1044203443.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[columnas_a_procesar] = df[columnas_a_procesar].applymap(lambda x: str(x).split('-', 1)[-1]).applymap(lambda x: x.strip())

In [13]:
# Verificación de Resultados
df

,IdSolicitud,EstadoId,FechaCierre,FechaInicio,FechaFin,iNroCompleto,iAuditor,iSubSite,iSite,iMasSite,...,iNCAsocMayor,iNCAsocMenor,iNCAsociadas,iAMAsociadas,iACAsocCriticas,iACAsocMayor,iACAsocMenor,iACAsociadas,CerradoADestiempo,CerradoAtiempo
365,3082,6,23/12/2019,01/06/2016,30/06/2016,AUD-S000366,TAlicia.Latino,RAFAELA,RAFAELA,CERRO VANGUARDIA,...,0,0,0,0,0,0,0,0,1,0
478,3197,6,29/01/2020,31/08/2016,29/09/2016,AUD-S000479,TNadia.Engler,GENERAL CV,GENERAL CV,CERRO VANGUARDIA,...,0,0,0,0,0,0,0,0,1,0
681,3415,6,05/10/2019,28/02/2017,30/03/2017,AUD-S000682,TNadia.Engler,GENERAL CN,GENERAL CN,CERRO NEGRO,...,0,0,0,0,0,0,0,0,1,0
795,3540,6,19/10/2019,31/05/2017,29/06/2017,AUD-S000796,TNadia.Engler,GENERAL CV,GENERAL CV,CERRO VANGUARDIA,...,0,0,0,0,0,0,0,0,1,0
945,3692,6,07/10/2019,31/12/2017,30/01/2018,AUD-S000946,TLucas.Barbieri,HMX,HMX,RAFAELA,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2583,42132,6,04/09/2023,01/06/2023,30/06/2023,AUD-S002586,TNicolas.Badra,GENERAL,CORDON DETONANTE,BELLA ITALIA,...,0,0,0,0,0,0,0,0,1,0
2584,45584,2,26/10/2023,01/10/2023,30/10/2023,AUD-S002587,TVeronica.Perea,RAFAELA,RAFAELA,RAFAELA,...,0,0,0,1,0,0,0,1,0,0
2585,45587,2,26/10/2023,01/10/2023,01/10/2023,AUD-S002588,TVeronica.Perea,RAFAELA,RAFAELA,RAFAELA,...,0,0,0,0,0,0,0,0,0,0
2586,45589,2,30/10/2023,01/12/2023,31/12/2023,AUD-S002589,TVeronica.Perea,MOVIMIENTOS,MOVIMIENTOS,RAFAELA,...,0,0,0,0,0,0,0,0,0,0
2587,45593,2,10/11/2023,01/12/2023,01/12/2023,AUD-S002590,TVeronica.Perea,MOVIMIENTOS,MOVIMIENTOS,RAFAELA,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df.describe()

,IdSolicitud,EstadoId,iPlanificadas,iFuture,iCanceladas,iCerradas,iEnEjecucion,iEjecConProcesosPendientes,iPendientedeHacer,iConProcesosPendientes,...,iNCAsocMayor,iNCAsocMenor,iNCAsociadas,iAMAsociadas,iACAsocCriticas,iACAsocMayor,iACAsocMenor,iACAsociadas,CerradoADestiempo,CerradoAtiempo
count,1072.000000,1072.000000,1072.0,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,...,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000
mean,22048.104478,5.835821,1.0,0.001866,0.015858,0.936567,0.001866,0.001866,0.035448,0.124067,...,0.024254,0.008396,0.039179,0.096082,0.007463,0.049440,0.029851,0.091418,0.548507,0.410448
std,13232.248326,0.793946,0.0,0.043173,0.124985,0.243854,0.043173,0.043173,0.184995,0.329812,...,0.186794,0.118047,0.283954,0.373121,0.086104,0.364611,0.378020,0.638802,0.497874,0.492145
min,3082.000000,2.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8863.750000,6.000000,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,19732.500000,6.000000,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,31461.250000,6.000000,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,45593.000000,6.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,3.000000,2.000000,5.000000,3.000000,1.000000,8.000000,10.000000,11.000000,1.000000,1.000000

In [15]:
# Guardar datos limpios

df.to_csv('Datos_Aud_limpias.csv',index=False)